### PR TITLE
update sha2 dep to 0.10

### PR DESCRIPTION
**Pull request by delta1**
Hey @LLFourn !

I'm working on https://github.com/comit-network/xmr-btc-swap/pull/948 to update the sha2 dependency, which requires it is also updated in this library. 

Is this acceptable? 

~~Apologies for the autoformatting to markdown docs, please let me know if that's a showstopper.~~

### CODE REVIEW

**Comment by LLFourn** [comment]
Hey @delta1 yep we should upgrade this for the next release. Please remove the auto-format markdown changes.

Looks like there will be quite a bit of work to do here across the various crates.

**Comment by delta1** [comment]
Removed the markdown changes. Will work on the tests :+1:

**Comment by delta1** [comment]
@LLFourn this is finally updated :sweat_smile:

**Comment by LLFourn** [comment]
Thanks @delta1!

**Pull request merged**
